# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3ee7f71bb8074c220c15d6b234149c4c1d8d7c375baee95320129a00496cf840ed0c3def186fed2482642fe7661a02a99625674fac3c08f529232998598f75a

test:
  secret_key_base: ffd28822f513ea1cbe57769de5b82aaedd8a28c548c662b385f3998b844f5226313beb7faead8f952904b78e8ae88d210b2033dc267234e288340c2eae0a6d33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
